FROM node:18-alpine

RUN mkdir -p /usr/app
WORKDIR /usr/app

ARG REACT_APP_GOOGLE_OAUTH_ID
ARG REACT_APP_BACKEND_URL
ARG REACT_APP_GOOGLE_LOGIN_URL
ARG REACT_APP_AWS_ACCESS_KEY_ID
ARG REACT_APP_AWS_SECRET_ACCESS_KEY
ARG REACT_APP_AWS_REGION
ARG REACT_APP_AWS_S3_BUCKET_NAME

ENV REACT_APP_GOOGLE_OAUTH_ID=${REACT_APP_GOOGLE_OAUTH_ID}
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
ENV REACT_APP_GOOGLE_LOGIN_URL=${REACT_APP_GOOGLE_LOGIN_URL}
ENV REACT_APP_AWS_ACCESS_KEY_ID=${REACT_APP_AWS_ACCESS_KEY_ID}
ENV REACT_APP_AWS_SECRET_ACCESS_KEY=${REACT_APP_AWS_SECRET_ACCESS_KEY}
ENV REACT_APP_AWS_REGION=${REACT_APP_AWS_REGION}
ENV REACT_APP_AWS_S3_BUCKET_NAME=${REACT_APP_AWS_S3_BUCKET_NAME}

# Install dependencies based on the preferred package manager
COPY . .

RUN npm install
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]